#!/bin/bash

SCRIPT_DIR="$(dirname "$(realpath "$0")")"

options_file="$SCRIPT_DIR/emulators_name.txt"

read_options_from_file() {
    mapfile -t options < "$options_file"
}

print_menu() {
    clear
    for i in "${!options[@]}"; do
        if [[ $i -eq $current_selection ]]; then
            echo -e "> \e[7m${options[i]}\e[0m"  # Highlight the selected option
        else
            echo "  ${options[i]}"
        fi
    done
}

handle_key() {
    read -rsn1 input
    if [[ $input == $'\x1b' ]]; then
        read -rsn2 -t 0.1 input
        case $input in
            '[A') # Up arrow
                ((current_selection--))
                if [[ $current_selection -lt 0 ]]; then
                    current_selection=$((${#options[@]} - 1))
                fi
                ;;
            '[B') # Down arrow
                ((current_selection++))
                if [[ $current_selection -ge ${#options[@]} ]]; then
                    current_selection=0
                fi
                ;;
        esac
    elif [[ $input == "" ]]; then
        # Enter key
        return 1
    fi
    return 0
}

execute_selection() {
    echo "lanching emulator: ${options[$current_selection]}"
    emulator=${options[$current_selection]}
    echo "running $emulator emulator"
       cd ~/android_sdk/emulator/
       ./emulator -avd $emulator &
}

main() {
    read_options_from_file
    current_selection=0
    while true; do
        print_menu
        handle_key
        if [[ $? -eq 1 ]]; then
            execute_selection
            break
        fi
    done
}

main
